export interface Question {
  slug: string;
  question: string;
  answer: string;
  category: 'getting-started' | 'tracking' | 'follow-up' | 'avoiding-bans';
  relatedSlugs: string[];
}

export const questions: Question[] = [
  {
    slug: 'how-to-create-whatsapp-link-for-business',
    question: 'How to create a WhatsApp link for my business?',
    answer: `You don't need the WhatsApp Business API or any technical setup. Here's the simplest way: take your WhatsApp number (the one customers already message you on), and turn it into a clickable link. Use a tool like Leadwa—enter your number, get a short link like leadwa.link/yourname, and share it anywhere: Instagram bio, Facebook ads, Google My Business, your website.\n\nWhen someone clicks it, WhatsApp opens with your number pre-filled. They tap once more to send the message. No friction, no app downloads. If you want to pre-fill a message ("Hi, I saw your ad"), you can do that too. The best part? You can track who clicked, when, and from where—so you know which ad or post is actually bringing in leads.\n\nLeadwa's free tier gives you the link and QR code forever. Paid plans (starting ₹199/month) add click tracking, follow-up alerts, and an inbox so no lead ever dies in your WhatsApp scroll.`,
    category: 'getting-started',
    relatedSlugs: ['whatsapp-link-with-prefilled-message', 'whatsapp-qr-code-for-shop-counter', 'track-whatsapp-clicks-free'],
  },
  {
    slug: 'whatsapp-link-with-prefilled-message',
    question: 'Can I create a WhatsApp link with a pre-filled message?',
    answer: `Yes, and it's one of the smartest things you can do for lead qualification. When you create your WhatsApp link, add a pre-fill message like "Hi, I'm interested in coaching classes for Class 10" or "I saw your Instagram ad for catering services." When the customer clicks your link, that message appears in their WhatsApp chat, ready to send.\n\nWhy does this matter? First, it saves them typing. Second, it qualifies the lead for you—you instantly know where they came from and what they want. Third, it reduces confusion: instead of "Hello" (and then you asking what they need), the conversation starts with context.\n\nHere's how to do it in Leadwa: enter your WhatsApp number, then fill the "Pre-fill message" field. That's it. The link you get will open WhatsApp with that message auto-typed. Use different pre-fill messages for different campaigns—"Saw your Facebook ad," "Scanned QR at counter," etc. That way, you know exactly which source is working.\n\nPro tip: Keep the pre-fill short and natural. Don't sound like a bot. "Hi, interested in your clinic services" works better than "Dear Sir/Madam, I am writing to enquire about..."`,
    category: 'getting-started',
    relatedSlugs: ['how-to-create-whatsapp-link-for-business', 'how-to-know-which-ad-brought-whatsapp-lead', 'whatsapp-link-for-instagram-bio'],
  },
  {
    slug: 'how-to-know-which-ad-brought-whatsapp-lead',
    question: 'How do I know which ad or post brought a WhatsApp lead?',
    answer: `This is the problem that kills most small businesses. You run three ads—one on Facebook, one on Instagram, one on Google. Leads start coming to your WhatsApp. But you have no idea which ad worked. So you keep spending on all three, even though only one is pulling its weight.\n\nHere's the fix: use a different trackable link for each ad. With Leadwa, create separate links with unique slugs: leadwa.link/fb-ad, leadwa.link/insta-ad, leadwa.link/google-ad. Put each link in its respective campaign. Now, when someone clicks, Leadwa records the source, timestamp, city, device, and even the referring URL if available.\n\nYour dashboard shows you exactly which link got the most clicks, which one converted to actual messages, and which one is just burning budget. No guesswork. No spreadsheets. Just clear data.\n\nBonus: Use different pre-fill messages per ad. Your Facebook ad link can pre-fill "I saw your Facebook offer," while Instagram pre-fills "Saw your Reel." That way, even if someone switches devices before messaging, you still know where they came from.\n\nLeadwa's Basic plan (₹199/month) includes unlimited link tracking. The free tier gives you the link, but not the click analytics—so if you're serious about knowing what works, the paid plan pays for itself in one saved bad-ad month.`,
    category: 'tracking',
    relatedSlugs: ['track-whatsapp-clicks-free', 'whatsapp-link-with-prefilled-message', 'whatsapp-link-for-instagram-bio'],
  },
  {
    slug: 'missed-call-to-whatsapp-auto-reply',
    question: 'Can I auto-reply on WhatsApp when someone gives a missed call?',
    answer: `Yes, but it's trickier than it sounds. If you're using the regular WhatsApp app (personal or Business app), there's no built-in missed-call-to-auto-reply feature. WhatsApp doesn't expose that trigger to third-party tools either.\n\nThe workaround most small businesses use: put your WhatsApp link everywhere you'd put a phone number. Instead of asking people to "call us," say "message us on WhatsApp." Print the QR code on your ads, vehicle wraps, visiting cards. When they scan it, WhatsApp opens instantly—no need for a missed call dance.\n\nIf you're already getting missed calls and want to convert them into WhatsApp messages, the manual way works best: when you see a missed call, send them a WhatsApp message immediately: "Hi, I saw your missed call. How can I help?" Most people prefer WhatsApp over callbacks anyway—it's less intrusive and gives them time to explain what they need.\n\nIf you really need automation (like auto-replying to thousands of missed calls), you'll need WhatsApp Business API—but that's expensive (₹3000+/month), requires approval, and is overkill for most small businesses. Stick with trackable links and QR codes. Cheaper, simpler, and works on your existing WhatsApp.`,
    category: 'follow-up',
    relatedSlugs: ['whatsapp-qr-code-for-shop-counter', 'how-to-follow-up-whatsapp-leads-without-being-spammy', 'whatsapp-business-app-vs-api-for-small-business'],
  },
  {
    slug: 'why-am-i-losing-whatsapp-leads',
    question: 'Why am I losing leads on WhatsApp?',
    answer: `Here's the brutal truth: you're not losing leads because they don't want your service. You're losing them because WhatsApp is designed for personal chat, not business. Every lead that messages you gets buried under family groups, spam, and delivery updates. By the time you scroll back to them, they've already messaged your competitor.\n\nThree specific reasons you're bleeding leads:\n\n1. **No visibility**: WhatsApp doesn't separate business from personal. A parent's enquiry about tuition classes sits between your cousin's wedding group and a Zomato OTP. You literally can't see it unless you scroll.\n\n2. **No reminders**: You reply to 40 leads today. Ten of them don't respond. WhatsApp doesn't tell you who went cold. A week later, that parent chose another coaching center—not because you were bad, but because you forgot to follow up.\n\n3. **No source tracking**: You ran Instagram ads, Facebook ads, and put a QR code at your shop counter. Leads are coming in. But you have no idea which channel is working. So you keep spending on all three, even though only one is pulling.\n\nLeadwa fixes all three. Every lead that clicks your link shows up in a dedicated dashboard with timestamp, source, location, device. You get alerts when someone clicks but doesn't message. You get reminders when a hot lead goes cold after 24 hours. No lead ever dies in the scroll again.`,
    category: 'tracking',
    relatedSlugs: ['how-to-follow-up-whatsapp-leads-without-being-spammy', 'how-to-know-which-ad-brought-whatsapp-lead', 'track-whatsapp-clicks-free'],
  },
  {
    slug: 'whatsapp-qr-code-for-shop-counter',
    question: 'How to create a WhatsApp QR code for my shop counter?',
    answer: `Dead simple. You want customers to scan a code at your counter and instantly message you on WhatsApp. Here's how:\n\n1. Create a WhatsApp link using Leadwa (or any tool). Enter your WhatsApp number, add a pre-fill message like "Hi, I'm at your shop counter and need help."\n\n2. Download the QR code. Leadwa gives you a high-res PNG that works perfectly for print.\n\n3. Print it big—at least 4x4 inches. Stick it near your billing counter, on your shop window, on pamphlets you hand out. The bigger and more visible, the better.\n\nWhen a customer scans it with their phone camera, WhatsApp opens with your number and the pre-filled message ready to send. One tap, done. No need to save your number, no friction.\n\nWhy is this better than just putting your phone number on the wall? Because:\n- They don't have to type your number (people hate that).\n- You know they came from the counter (if you're tracking clicks with Leadwa).\n- It's contactless—they can scan and message you later when they get home, instead of forgetting.\n\nPro tip: Use a different QR code for different locations. If you have two shops, use leadwa.link/shop1 and leadwa.link/shop2. That way, you know which location is bringing in more enquiries—and you can staff accordingly.`,
    category: 'getting-started',
    relatedSlugs: ['how-to-create-whatsapp-link-for-business', 'track-whatsapp-clicks-free', 'whatsapp-link-with-prefilled-message'],
  },
  {
    slug: 'how-to-follow-up-whatsapp-leads-without-being-spammy',
    question: 'How do I follow up with WhatsApp leads without being spammy?',
    answer: `The line between helpful and annoying is thinner than you think. Here's the rule: one follow-up is professional, two is persistent, three is spam.\n\nHere's the cadence that works:\n\n**Day 1**: They message you, you reply. Clear, helpful, not salesy. If they don't respond, wait.\n\n**Day 2 (24 hours later)**: Send one gentle nudge. "Hi [name], just checking if you had any other questions about [service]. Happy to help!" Keep it light, not desperate.\n\n**Day 4-5**: If still no reply, send a final message with value. Not "Are you interested?" but "Here's a quick tip that might help you decide: [insert one useful thing]." Then say, "No pressure—reach out anytime."\n\nAfter that? Stop. If they want your service, they'll come back. Chasing beyond this point kills your credibility.\n\nNow, the problem: how do you remember to follow up? You're juggling 50 leads. You can't manually track who replied and who didn't. This is where Leadwa's follow-up alerts save you. The system watches every lead. If someone clicks your link but doesn't message, you get an alert. If they message but go cold for 24 hours, you get a reminder. No spreadsheets, no calendar entries—just smart nudges when it matters.\n\nOne last thing: never use WhatsApp broadcast lists for cold leads. That's spam. Broadcast is for customers who've already bought from you and opted in for updates. Leads who haven't converted yet? One-on-one messages only.`,
    category: 'follow-up',
    relatedSlugs: ['why-am-i-losing-whatsapp-leads', 'missed-call-to-whatsapp-auto-reply', 'how-to-stop-whatsapp-number-getting-banned'],
  },
  {
    slug: 'whatsapp-link-for-instagram-bio',
    question: 'How to add a WhatsApp link to my Instagram bio?',
    answer: `Instagram only lets you put one clickable link in your bio. Make it count. Don't waste it on "linktr.ee/yourname" with ten random links. Put your WhatsApp link there—direct, no middleman.\n\nHere's how:\n\n1. Create a short WhatsApp link. Use Leadwa and pick a memorable slug like leadwa.link/yourname. The shorter, the better—people might type it if they see it in a screenshot.\n\n2. Add a pre-fill message specific to Instagram. Something like "Hi, I came from your Instagram" so you know immediately that this lead is from IG, not Facebook or Google.\n\n3. Go to Instagram → Edit Profile → Website. Paste your WhatsApp link there. Done.\n\nNow, when someone clicks the link in your bio, WhatsApp opens with your number and the pre-filled message. One tap to send. No forms, no "Leave your details," no friction.\n\nWhy this works better than Instagram DMs: People are more likely to reply on WhatsApp than IG. WhatsApp is where real conversations happen—buying decisions, price negotiations, appointment bookings. Instagram DMs get buried under spam and meme tags.\n\nPlus, with Leadwa's click tracking (Basic plan, ₹199/month), you'll know exactly how many people clicked your bio link, what time they clicked, and which posts drove the most traffic. That way, you double down on what works.`,
    category: 'getting-started',
    relatedSlugs: ['how-to-create-whatsapp-link-for-business', 'whatsapp-link-with-prefilled-message', 'how-to-know-which-ad-brought-whatsapp-lead'],
  },
  {
    slug: 'track-whatsapp-clicks-free',
    question: 'How to track WhatsApp link clicks for free?',
    answer: `Short answer: Leadwa's free tier gives you the link and QR code, but not the click tracking. For tracking, you need the Basic plan (₹199/month). But here's why it's worth it—and what you get.\n\nThe free way (no tracking): You can create a WhatsApp link for free using any tool, including Leadwa. You get a working link like leadwa.link/yourname and a QR code. Share it anywhere. When people click, WhatsApp opens. But you have zero visibility into who clicked, when, or from where. It's a black box.\n\nThe paid way (with tracking): Leadwa's Basic plan logs every click: timestamp, location (city-level), device (mobile/desktop), referring URL (if available). You see exactly which link is performing, which ad is working, which post is driving traffic. You also get follow-up alerts—when someone clicks but doesn't message, or when a lead goes cold, you get a nudge.\n\nWhy pay ₹199/month instead of using a free tool? Because one bad ad campaign costs you more than ₹199. If you're spending ₹5000/month on Facebook ads and have no idea which ad is bringing leads, you're flying blind. Leadwa's tracking pays for itself in the first week by showing you what to kill and what to scale.\n\nThat said, if you're just testing the waters—running a single link, no ads, just want a WhatsApp link for your Instagram bio—the free tier is fine. But the moment you start running multiple campaigns or paying for ads, tracking becomes non-negotiable.`,
    category: 'tracking',
    relatedSlugs: ['how-to-know-which-ad-brought-whatsapp-lead', 'why-am-i-losing-whatsapp-leads', 'whatsapp-link-for-instagram-bio'],
  },
  {
    slug: 'whatsapp-business-app-vs-api-for-small-business',
    question: 'WhatsApp Business app vs API: which one for small business?',
    answer: `Here's the breakdown without the jargon:\n\n**WhatsApp Business app** (free): This is the one you download from the Play Store or App Store. It's designed for solo entrepreneurs and small teams. You get:\n- Business profile (address, hours, website)\n- Quick replies (saved messages you send often)\n- Labels (tag chats as "New lead," "Pending," etc.)\n- Catalog (show products with prices)\n\nLimits: Only one person can use it at a time. If you have a team, they can't all reply from the same number. You also can't automate anything—no auto-replies to missed calls, no drip campaigns, no bulk messaging (thank god, honestly).\n\n**WhatsApp Business API** (₹3000+/month): This is for big companies. Banks, e-commerce brands, airlines. You get:\n- Multiple team members on the same number\n- Automation (chatbots, auto-replies, order updates)\n- Integration with CRMs, ERPs, ticketing systems\n- Bulk messaging (but only to people who've opted in)\n\nLimits: Expensive. Requires approval from Meta. Needs a tech team to set up. Overkill for 99% of small businesses.\n\n**For most small businesses, the answer is: WhatsApp Business app + Leadwa.** You get the simplicity of the app, plus Leadwa's click tracking, follow-up alerts, and lead dashboard. You don't need API-level automation—you just need to make sure no lead ever dies in your WhatsApp scroll. That's what Leadwa does.`,
    category: 'getting-started',
    relatedSlugs: ['missed-call-to-whatsapp-auto-reply', 'how-to-create-whatsapp-link-for-business', 'why-am-i-losing-whatsapp-leads'],
  },
  {
    slug: 'best-way-to-get-leads-on-whatsapp-india',
    question: 'What is the best way to get leads on WhatsApp in India?',
    answer: `Stop waiting for people to save your number and message you. That's friction. Remove it.\n\nHere's the playbook:\n\n**1. Make your WhatsApp number clickable everywhere.** Not just a phone number—an actual clickable link. Put it in your Instagram bio, Facebook page, Google My Business, website footer, email signature. When someone clicks, WhatsApp opens instantly. No copying, no pasting, no "I'll message you later" (they won't).\n\n**2. Use QR codes offline.** Print them on your visiting cards, shop counter, vehicle wraps, pamphlets, newspaper ads. People scan with their phone camera, WhatsApp opens, they send a message. Works even if they're not tech-savvy.\n\n**3. Pre-fill messages.** When they click your link, auto-fill a message like "Hi, I'm interested in coaching classes." They tap Send, done. This qualifies the lead for you—you instantly know what they want and where they came from.\n\n**4. Track every source.** Use different links for different campaigns. leadwa.link/fb-ad for Facebook, leadwa.link/insta for Instagram, leadwa.link/shop for counter QR. Now you know exactly which channel is pulling.\n\n**5. Follow up religiously.** Most leads don't convert on the first message. They message you, you reply, they go silent. You need reminders. Leadwa sends you alerts when a lead clicks but doesn't message, or when a conversation goes cold after 24 hours.\n\nThe businesses winning on WhatsApp in India aren't the ones with the best product. They're the ones who reply first, follow up consistently, and track what's working. That's it.`,
    category: 'getting-started',
    relatedSlugs: ['how-to-create-whatsapp-link-for-business', 'whatsapp-qr-code-for-shop-counter', 'how-to-know-which-ad-brought-whatsapp-lead'],
  },
  {
    slug: 'how-to-stop-whatsapp-number-getting-banned',
    question: 'How to stop my WhatsApp number from getting banned?',
    answer: `WhatsApp bans happen when you violate their rules—usually by spamming people who haven't opted in. Here's how to stay safe:\n\n**What gets you banned:**\n1. Sending the same message to 50+ people in a short time (bulk messaging)\n2. Messaging people who haven't saved your number or messaged you first\n3. Using third-party apps to automate WhatsApp (unofficial WhatsApp mods, auto-reply bots)\n4. Getting reported by multiple users for spam\n5. Sending links that WhatsApp flags as suspicious (URL shorteners can trigger this)\n\n**How to avoid a ban:**\n1. Only message people who've reached out to you first, or who've explicitly given you their number.\n2. Don't use broadcast lists for cold leads. Broadcast is only for existing customers who've opted in.\n3. Don't send the exact same message to everyone. Personalize it—even slightly.\n4. Use WhatsApp Business app or regular WhatsApp, not modded apps.\n5. If you're sending links, use your own domain (leadwa.link/yourname) instead of bit.ly or other shorteners. WhatsApp trusts branded links more.\n\n**What if you're already banned?**\nIf it's a temporary ban (24-48 hours), wait it out. Don't try to bypass it. If it's permanent, you'll need a new number—and this time, follow the rules.\n\n**The Leadwa advantage:** Since Leadwa links only direct people to message you (they initiate the chat), you're never cold-messaging anyone. That's inherently safer than broadcast lists or bulk SMS-style campaigns. The lead clicks your link, they send the first message, you reply. Clean, compliant, no spam flags.`,
    category: 'avoiding-bans',
    relatedSlugs: ['how-to-follow-up-whatsapp-leads-without-being-spammy', 'whatsapp-business-app-vs-api-for-small-business', 'best-way-to-get-leads-on-whatsapp-india'],
  },
];
